# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

# Base info
mc_version=26.1.2
neo_version=26.1.2.94
mod_group=com.mrbysco.dimpaintings
mod_id=dimpaintings
mod_archive_name=Dimensional-Paintings

#Publishing
mod_name=Dimensional Paintings
curseforge_id=480500
modrinth_id=Fp8IRgq4

# Version
version=10.0.0

# Dependencies
jei_minecraft=26.1.2
jei_version=29.6.2.31
jade_id=8326300
#top_id=6106998