modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/Dimensional-Paintings/issues"
license="MIT"

[[mods]]
modId="dimpaintings"
version="${file.jarVersion}"
displayName="Dimensional Paintings"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dimensional-paintings"
authors="Mrbysco, ShyNieke"
description='''
Just jump in :)
'''
[[dependencies.dimpaintings]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.21.7,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.dimpaintings]]
modId="neoforge"
type="REQUIRED"
versionRange="[21.7.0-beta,)"
ordering="NONE"
side="BOTH"